export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOAD_SUCCESS = "USERS_LOAD_SUCCESS";
export const USERS_LOAD_ERROR = "USERS_LOAD_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_CLIENT_LOADING = "ADD_CLIENT_LOADING";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_ERROR = "ADD_CLIENT_ERROR";
