export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOAD_SUCCESS = "USERS_LOAD_SUCCESS";
export const USERS_LOAD_ERROR = "USERS_LOAD_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_CLIENT_LOADING = "ADD_CLIENT_LOADING";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_ERROR = "ADD_CLIENT_ERROR";

export const ADD_MEASUREMENTS_LOADING = "ADD_MEASUREMENTS_LOADING";
export const ADD_MEASUREMENTS_SUCCESS = "ADD_MEASUREMENTS_SUCCESS";
export const ADD_MEASUREMENTS_ERROR = "ADD_MEASUREMENTS_ERROR";

export const ADD_STAFF_LOADING = "ADD_STAFF_LOADING";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_ERROR = "ADD_STAFF_ERROR";

export const GET_SUPPLY_LOADING = "GET_SUPPLY_LOADING";
export const GET_SUPPLY_SUCCESS = "GET_SUPPLY_SUCCESS";
export const GET_SUPPLY_ERROR = "GET_SUPPLY_ERROR";

export const GET_ORDER_LOADING = "GET_ORDER_LOADING";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const ADD_ORDER_LOADING = "ADD_ORDER_LOADING";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR";

export const ADD_SALE_LOADING = "ADD_SALE_LOADING";
export const ADD_SALE_SUCCESS = "ADD_SALE_SUCCESS";
export const ADD_SALE_ERROR = "ADD_SALE_ERROR";

export const UPDATE_ORDER_LOADING = "UPDATE_ORDER_LOADING";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

export const CREATE_SUPPLY_LOADING = "CREATE_SUPPLY_LOADING";
export const CREATE_SUPPLY_SUCCESS = "CREATE_SUPPLY_SUCCESS";
export const CREATE_SUPPLY_ERROR = "CREATE_SUPPLY_ERROR";

export const UPDATE_SUPPLY_LOADING = "UPDATE_SUPPLY_LOADING";
export const UPDATE_SUPPLY_SUCCESS = "UPDATE_SUPPLY_SUCCESS";
export const UPDATE_SUPPLY_ERROR = "UPDATE_SUPPLY_ERROR";

export const UPDATE_MEASUREMENTS_LOADING = "UPDATE_MEASUREMENTS_LOADING";
export const UPDATE_MEASUREMENTS_SUCCESS = "UPDATE_MEASUREMENTS_SUCCESS";
export const UPDATE_MEASUREMENTS_ERROR = "UPDATE_MEASUREMENTS_ERROR";

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
